import clsx from 'clsx';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { SVGComposableLight } from '@/svg';
import Head from 'next/head';
import { Img } from '@/components/common/Img';

export const Header = () => {
	const router = useRouter();
	return (
		<header className="h-full w-full">
			<Head>
				<title>SmartContract Dev viewer</title>
				<meta name="description" content="Generated by Goblins" />
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
				<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
				<link href="/fonts/Metropolis-Regular.otf" type="font/otf" crossOrigin="anonymous" as="font" rel="preload" />
				<link href="/fonts/Wavehaus-95SemiBold.otf" type="font/otf" crossOrigin="anonymous" as="font" rel="preload" />
				<link href="/fonts/Wavehaus-66Book.otf" type="font/otf" crossOrigin="anonymous" as="font" rel="preload" />
			</Head>
			<div className="mx-auto flex w-full items-center justify-between px-10 py-[33.5px] lg:w-lg lg:px-[6px]">
				<Link href="/" passHref>
					<a className={clsx('flex items-center gap-4', { 'pointer-events-none': router.pathname === '/' })}>
						<SVGComposableLight />
						<div className="mb-1 flex items-center gap-4">
							<p className="font-wavehaus text-[25px]">x</p>
							<Img className="w-10" src="/icons/external/cosmwasm_logo.png" />
						</div>
						<figure className="h-6 w-[1px] bg-titanium.3" />
						<p className="font-metropolis text-[25px]">contract dev viewer</p>
					</a>
				</Link>
			</div>
		</header>
	);
};
